import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/nav/NavBar";
import songReducer from "../hooks/songSlice";
import { Provider } from "react-redux";
import createSagaMiddleware from "redux-saga";
import { configureStore } from "@reduxjs/toolkit";
import store from "@/store/store";
import SongProvider from "@/providers/SongProvider";
import { Toaster } from "react-hot-toast";
// import rootReducer from './yourRootReducer'; // Import your actual root reducer

// sagaMiddleware.run(songSaga);
const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "music-player",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} text-slate-700`}>
        <SongProvider>
          <div className="flex flex-col min-h-screen">
            <NavBar />
            <main className="flex-grow">
            <Toaster position="top-center" />
              {children}</main>
          </div>
        </SongProvider>
        {/* </Provider> */}
      </body>
    </html>
  );
}
